import expressAsyncHandler from "express-async-handler";

export const Register = expressAsyncHandler((req, res) => {});
export const LogIn = expressAsyncHandler((req, res) => {});
export const LogOut = expressAsyncHandler((req, res) => {});
export const forgetPassword = expressAsyncHandler((req, res) => {});
export const resetPassword = expressAsyncHandler((req, res) => {});
export const changePassword = expressAsyncHandler((req, res) => {});
export const myInfo = expressAsyncHandler((req, res) => {});
export const updateMyInfo = expressAsyncHandler((req, res) => {});
export const deleteAccount = expressAsyncHandler((req, res) => {});
export const getAllSession = expressAsyncHandler((req, res) => {});
export const deleteSession = expressAsyncHandler((req, res) => {});
export const getRoles = expressAsyncHandler((req, res) => {});
export const createNewRole = expressAsyncHandler((req, res) => {});
export const updateRole = expressAsyncHandler((req, res) => {});
export const deleteRole = expressAsyncHandler((req, res) => {});
export const refreshToken = expressAsyncHandler((req, res) => {});
export const revokeToken = expressAsyncHandler((req, res) => {});
export const setup2Fa = expressAsyncHandler((req, res) => {});
export const verify2Fa = expressAsyncHandler((req, res) => {});
