export { default as AuthController } from './auth.controller';
export { default as StudentController } from './student.controller';
export { default as ParentController } from './parent.controller';
export { default as AttendanceController } from './attendance.controller';
export { default as ApiLogController } from './apiLog.controller';
export { default as RoleController } from './role.controller';
export { default as EventController } from './event.controller';
export { default as BillController } from './bill.controller';
export { default as ClassController } from './class.controller';
export { default as ExamController } from './exam.controller';
// export { default as GroupController } from './group.controller';
// export { default as FeeController } from './fee.controller';
export { default as ResultController } from './result.controller';
export { default as SessionController } from './session.controller';
export { default as OrganizationController } from './organization.controller';
export { default as TokenController } from './token.controller';
export { default as PermissionController } from './permission.controller';
export { default as ComplaintController } from './complaint.controller';
export { default as TransactionController } from './transaction.controller';
export { default as TeacherController } from './teacher.controller';
export { default as AdmissionController } from './admission.controller';
export { default as ChatController } from './chat.controller';
export { default as UserController } from './user.controller';
