// RESOURCE_ACTION , example: USER_DELETE, USER_BAN
/*
    XYZ : {
        READ: 'XYZ_READ',
        WRITE: 'XYZ_WRITE',
        UPDATE: 'XYZ_UPDATE',
        DELETE: 'XYZ_DELETE'
    }
*/
const PERMISSIONS = {
  ROLE: {
    READ: 'ROLE_READ',
    WRITE: 'ROLE_WRITE',
    UPDATE: 'ROLE_UPDATE',
    DELETE: 'ROLE_DELETE',
  },
  PERMISSION: {
    READ: 'PERMISSION_READ',
    WRITE: 'PERMISSION_WRITE',
    UPDATE: 'PERMISSION_UPDATE',
    DELETE: 'PERMISSION_DELETE',
  },
  USER: {
    READ: 'USER_READ',
    WRITE: 'USER_WRITE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },
  CATEGORY: {
    READ: 'CATEGORY_READ',
    WRITE: 'CATEGORY_WRITE',
    UPDATE: 'CATEGORY_UPDATE',
    DELETE: 'CATEGORY_DELETE',
  },
  CONDITION: {
    READ: 'CONDITION_READ',
    WRITE: 'CONDITION_WRITE',
    UPDATE: 'CONDITION_UPDATE',
    DELETE: 'CONDITION_DELETE',
  },
  FORMAT: {
    READ: 'FORMAT_READ',
    WRITE: 'FORMAT_WRITE',
    UPDATE: 'FORMAT_UPDATE',
    DELETE: 'FORMAT_DELETE',
  },
  PRODUCT: {
    READ: 'PRODUCT_READ',
    WRITE: 'PRODUCT_WRITE',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
  },
};
const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  USER: 'USER',
};

const EMAIL_TYPES = {
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
};
export default { PERMISSIONS, ROLES, EMAIL_TYPES };
